# Generated by Django 4.2.2 on 2023-07-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sochial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
