# Generated by Django 4.2.2 on 2023-07-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sochial', '0002_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
