# Generated by Django 4.2.2 on 2023-07-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sochial', '0006_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=25),
        ),
    ]
